### ISSUE TITLE
Error with "new ExtraDimensionsPackage(this)" inside MainApplication.java

### ISSUE THREAD

**Issue by Larney11** [Sunhat/react-native-extra-dimensions-android#13] opened 2016-07-26 15:22 UTC
I have followed all the steps listed in the README.md.

I am unable to build my project and this error appears:

![screen shot 2016-07-26 at 16 18 22](https://cloud.githubusercontent.com/assets/20336495/17143850/b1d4c072-534c-11e6-98e0-a1b5b5f92173.png)

I am using React-Native version 0.29.2

Please help!

**Comment by yozi-developer** [comment] 2016-07-27 14:23
Duplicate of https://github.com/jaysoo/react-native-extra-dimensions-android/issues/9

**Comment by Tamal** [comment] 2016-07-28 06:48
I think @BelinChung fixed this. Not sure about PR status. This fork works with RN 0.30

npm install --save https://github.com/BelinChung/react-native-extra-dimensions-android

thanks

**Comment by Larney11** [comment] 2016-08-06 12:16
Thanks, Yes he did.

**Solution**
[Check out this StackOverflow solution](http://stackoverflow.com/questions/38592302/react-native-android-how-to-use-getrealdimensions-dimensions-is-not-working/38804173#38804173).
@itinance

**Closed as completed** 2016-08-06 12:18 UTC
